#!/bin/sh
set -e

if [ "$USER" == 'root' ]; then
  echo 'error: cannot run `doasedit` as root' >&2
  exit
elif ! [ -x "$(command -v doas)" ]; then           # Check if doas is installed. If it isn't installed, warn the user.
  echo 'error: could not find command `doas`' >&2
  exit
elif [ -z "$1" ]; then                             # Check if there was any input. If there was no input, abort.
  echo "error: no input given" >&2
  exit
elif [ -d "$1" ]; then                             # Check if the inputted file is a directory. If it is a directory, abort.
  echo "error: $1: is a directory" >&2
  exit
fi

tempDir="$(mktemp -d)"               # Create the directory for the temporary file. Example: /tmp/tmp.rYT4bE3AiS/
tempFile="$tempDir/$(basename $1)"   # Create the temporary file.  Example: /usr/bin/bash -> /tmp/tmp.rYT4bE3AiS/bash

if [ -e "$1" ]; then                 # Make sure file exists before copying. If it doesn't, proceed without copying
  cp "$1" "$tempFile"
fi

eval "$EDITOR $tempFile"             # Start writing to the file. Use $EDITOR as the editor.

if (cmp -s $1 $tempFile) || [ -f $tempFile ]; then
  echo "no changes written to $1"
else
  doas cp $tempFile $1
  rm $tempDir -rf

  echo "wrote changes to file $1"
fi
